slam_toolbox:
  ros__parameters:
    use_sim_time: true                # 시뮬레이터면 true
    base_frame: base_link             # 반드시 센서 frame_id와 같게!
    odom_frame: odom
    map_frame: map
    scan_topic: scan                  # /scan
    scan_queue_size: 200
    resolution: 0.05
    max_laser_range: 10.0
    minimum_time_interval: 0.4
    transform_publish_period: 0.05
    map_publish_period: 1.0
    map_update_interval: 2.0
    publish_map_to_odom: true

